# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               "Linux Devops"
tagline:             'a kind of life'
description:         'All my ramblings mainly about Linux and Devops'
url:                 https://abacao.github.io
baseurl:             'https://abacao.github.io'
paginate:            5
google_analytics:    'UA-97265376-1'

# About/contact
author:
  name:              André Bação
  email:             email@bacao.pt

# Custom vars
version:             1.0.5
