# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true
plugins:
  - jekyll-feed

# Setup
title:               "Linux DevOps"
tagline:             'a kind of life'
description:         'All my ramblings mainly about Linux and DevOps'
url:                 http://abacao.github.io
baseurl:             'http://abacao.github.io'
paginate:            5
google_analytics:    'UA-97265376-1'

# About/contact
author:
  name:              André Bação
  email:             email@bacao.pt

# Custom vars
version:             1.0.8
